server:
  port: 6665
spring:
  application:
    name: docker
  #resources:
  #  add-mappings: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource    #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver   #此处不对哈  mysql驱动包
    url: jdbc:mysql://localhost:3306/db2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  redis:
    port: 6379
    host: 47.106.68.235
    password: 2024go
mybatis-plus:
  type-aliases-package: com.docker.bean
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    map-underscore-to-camel-case: true
    #开启二级缓存
    cache-enabled: true